prepare: try to detect the commit multiple times
Solves this problem we sometimes encounter on CICD:

pathspec 'Too many requests' did not match any file(s) known to git

This is because without -f option when there was an error, like
typically for HTTP throttling, the variable gets populated with the
response body. The fix is to wait for 2xx replied several times and also
to skip populating the variable on errors and end the script properly.

diff --git a/prepare b/prepare
--- a/prepare
+++ b/prepare
@@ -14,7 +14,14 @@ function cleanup {
 }
 trap cleanup ERR
 
-TERRAFORM_COMMIT=$(curl -L "$CUSTOM_ENV_CI_PROJECT_URL/-/raw/$CUSTOM_ENV_CI_COMMIT_SHA/schutzbot/terraform")
+TERRAFORM_COMMIT=$(curl -fL --retry 5 --retry-delay 15 --retry-all-errors \
+    "$CUSTOM_ENV_CI_PROJECT_URL/-/raw/$CUSTOM_ENV_CI_COMMIT_SHA/schutzbot/terraform")
+
+# Check if the variable is empty before proceeding (because of curl option -f)
+if [ -z "$TERRAFORM_COMMIT" ]; then
+    echo "ERROR: Failed to fetch TERRAFORM_COMMIT after multiple retries."
+    exit 1
+fi
 
 # Get all terraform config files
 TEMP=$(mktemp -d)
